name: Build and deploy on validation environment

on:
  push:
    branches: [ validation ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Create target directory
      run: |
          sudo mkdir /var/www/bo-api
          cd /var/www/bo-api

    - uses: actions/checkout@v2

    - name: Create and install venv
      run: |
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip install -r requirements.txt

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VALIDATION_ENV_SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.VALIDATION_ENV_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avzr --exclude=config/config.py ./ ${{ secrets.VALIDATION_ENV_USER }}@${{ secrets.VALIDATION_ENV_HOST }}:/var/www/bo-api

    - name: Reload web server
      run: sudo service apache2 reload