name: Build and deploy on validation environment

on:
  push:
    branches: [ validation ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Create target directory
      run: |
          sudo mkdir /var/www/bo-api

    - uses: actions/checkout@v2

    - name: Copy project to target dir
      run: sudo cp -R ./ /var/www/bo-api

    - name: cache python venv
      working-directory: /var/www/bo-api
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: install venv
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends python3 python3-venv

    - name: install requirements
      working-directory: /var/www/bo-api
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip3 install -U pip setuptools
        pip3 install -r requirements.txt
    - name: show built content
      run: find .

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VALIDATION_ENV_SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H {{ secrets.VALIDATION_ENV_HOST }} >> ~/.ssh/known_hosts

    - name: rsync
      working-directory: /var/www/bo-api
      run: rsync -r --exclude=.git --exclude=.gitignore --exclude=.github --exclude=config/config.py ./ boapi@{{ secrets.VALIDATION_ENV_HOST }}:/var/www/bo-api
