name: Build and deploy on production environment

on:
  push:
    branches: [ "remi/cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: install venv
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends python3 python3-venv

    - name: install requirements
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip3 install -U pip setuptools
        pip3 install -r requirements.txt

    - name: show built content
      run: find .
