name: Run PyCQA Prospector
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: "config/config.py.sample"
          target: "config/config.py"
          
      - name: Run PyCQA Prospector
        run: prospector -i venv/ --no-autodetect
