name: Run Python Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: CYBERLUX_TEST
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5sapt-get
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start MySQL server and create user
        run: |
          sudo systemctl start mysql
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'cyberlux'@'localhost' IDENTIFIED BY 'DBDevSMILE20';"
      - name: Initialize database
        run: |
          sudo mysql -e "CREATE DATABASE `CYBERLUX_TEST` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          sudo mysql CYBERLUX_TEST < db/sql/cyberlux_structure.sql
      - name: Run unit tests with coverage
        run: |
          cp config/config.py.sample config/config.py
          coverage run --source=resource,utils,db,decorator -m unittest discover && coverage report