name: Run Python Unit Tests
on:
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Service container to run with "laravel-test-withdb"
    services:
      # Label used to access the service container
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: CYBERLUX
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          source: "config/config.py.sample"
          target: "config/config.py"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run unit tests with coverage
        env:
          DB_NAME: CYBERLUX
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: coverage run --source=resource,utils,db,decorator -m unittest discover && coverage report 
